<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>FileGroup</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Tests\**" />
    <Compile Remove="Demo\**" />
    <Compile Remove="DemoLocal\**" />
    <None Include="Tests\**" />
    <None Include="Demo\**" />
    <None Include="DemoLocal\**" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos/engine.proto" GrpcServices="Client" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.27.0" />
    <PackageReference Include="Grpc.Net.Client" Version="2.63.0" />
    <PackageReference Include="Grpc.Tools" Version="2.63.0" PrivateAssets="All" />
  </ItemGroup>

</Project>
